### ISSUE TITLE
Manage MetaData Modal - Scroll Bar Needed

### ISSUE THREAD

**Issue by techieph** [Aroliant/felix#15]
In Bucket Page ->  Object -> Manage -> MetaData Model 

When more than 2 of additional Meta Key-Value Added, there one could not select a Save Button, it would be better if a Scroll Bar is added.

**Comment by techieph** [comment]
![Capture](https://user-images.githubusercontent.com/31580421/70213162-b8063280-175e-11ea-98fb-fe01abe57c65.PNG)

**Comment by nkr96** [comment]
@techieph @JacobSamro It's done.

**Comment by JacobSamro** [comment]
@nkr96 Next time reference the issue on your commit messages.
