### ISSUE TITLE
Move Folder Modal - Scroll Bar Needed

### ISSUE THREAD

**Issue by techieph** [Aroliant/felix#8]
Move Folder, when the tree structure or hierrarchial structure of tree is huge, the move folder modal ( which pop up on clicking Move Folder Options in Bucket Page ) is huge and is out of scope of reaching the move or cancel button of the move folder modal. It would be better if there is a scroll bar such that the button in the move folder model can be accessed for huge tree structures buckets

**Comment by nkr96** [comment]
@techieph @JacobSamro  I have pushed a fix, pull my changes and again.
